name: avrcrm
description: AVRCRM - CRM, Finance, Inventory and Marketing SaaS starter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.13.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_database: ^12.4.7
  provider: ^6.1.5+1
  file_picker: ^12.0.0
  csv: ^6.0.0
  excel: ^4.0.6
  intl: ^0.20.2
  path_provider: ^2.1.6
  pdf: ^3.11.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  path_provider_foundation: 2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/avrcrm_logo.png