// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9iUaannrRTN6ASz8LrFKp2900lODzXQ',
    appId: '1:40219428323:web:avrcrm',
    messagingSenderId: '40219428323',
    projectId: 'avrcrm-3d256',
    authDomain: 'avrcrm-3d256.firebaseapp.com',
    storageBucket: 'avrcrm-3d256.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI9iUaannrRTN6ASz8LrFKp2900lODzXQ',
    appId: '1:40219428323:android:39e9eff004d5903a744cd6',
    messagingSenderId: '40219428323',
    projectId: 'avrcrm-3d256',
    storageBucket: 'avrcrm-3d256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9iUaannrRTN6ASz8LrFKp2900lODzXQ',
    appId: '1:40219428323:ios:avrcrm',
    messagingSenderId: '40219428323',
    projectId: 'avrcrm-3d256',
    storageBucket: 'avrcrm-3d256.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9iUaannrRTN6ASz8LrFKp2900lODzXQ',
    appId: '1:40219428323:macos:avrcrm',
    messagingSenderId: '40219428323',
    projectId: 'avrcrm-3d256',
    storageBucket: 'avrcrm-3d256.firebasestorage.app',
  );
}
